# Generated by Django 4.0.4 on 2022-05-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleQuestion',
            fields=[
                ('qid', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='qid')),
                ('question', models.CharField(max_length=300, verbose_name='question')),
                ('optionA', models.CharField(max_length=100, verbose_name='A')),
                ('optionB', models.CharField(max_length=100, verbose_name='B')),
                ('optionC', models.CharField(max_length=100, verbose_name='C')),
                ('optionD', models.CharField(max_length=100, verbose_name='D')),
                ('answer', models.CharField(max_length=5, verbose_name='answer')),
                ('explain', models.CharField(max_length=500, verbose_name='explain')),
            ],
        ),
    ]
