# Generated by Django 4.0.4 on 2022-05-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='singlequestion',
            table='single_question',
        ),
    ]
