# Generated by Django 4.0.4 on 2022-05-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_singlequestion_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlequestion',
            name='qid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='qid'),
        ),
    ]
